-- MySQL Script generated by MySQL Workbench
-- 07/23/18 21:12:51
-- 03/21/19 16:37:17
-- Model: New Model    Version: 1.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yumi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yumi` DEFAULT CHARACTER SET utf8mb4 ;
USE `yumi` ;

-- -----------------------------------------------------
-- Table `yumi`.`angle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`angle` (
  `idangle` INT(11) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idangle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`arm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`arm` (
  `idarm` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(3) NULL DEFAULT 'rgt',
  PRIMARY KEY (`idarm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`object` (
  `idobject` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idobject`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `yumi`.`assembly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`assembly` (
  `idassembly` INT(11) NOT NULL AUTO_INCREMENT,
  `idobject0` INT(11) NULL DEFAULT NULL,
  `idobject1` INT(11) NULL DEFAULT NULL,
  `rotmat0` VARCHAR(360) NULL DEFAULT NULL,
  `rotmat1` VARCHAR(360) NULL DEFAULT NULL,
  `assdirect1to0` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`idassembly`),
  INDEX `idobject0_idx` (`idobject0` ASC),
  INDEX `idobject1_idx` (`idobject1` ASC),
  CONSTRAINT `assembly_idobject0`
    FOREIGN KEY (`idobject0`)
    REFERENCES `yumi`.`object` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `assembly_idobject1`
    FOREIGN KEY (`idobject1`)
    REFERENCES `yumi`.`object` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'by default assembly involves two objects';

-- -----------------------------------------------------
-- Table `yumi`.`assemblyx`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`assemblyx` (
  `idassemblyx` INT(11) NOT NULL AUTO_INCREMENT,
  `idassembly` INT(11) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  PRIMARY KEY (`idassemblyx`),
  INDEX `assemblyx_idassembly_idx` (`idassembly` ASC),
  CONSTRAINT `assemblyx_idassembly`
    FOREIGN KEY (`idassembly`)
    REFERENCES `yumi`.`assembly` (`idassembly`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'trabsformed assembly\nSince assembly is always goal, only free is saved';

-- -----------------------------------------------------
-- Table `yumi`.`hand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`hand` (
  `idhand` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idhand`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`freeairgrip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`freeairgrip` (
  `idfreeairgrip` INT(11) NOT NULL AUTO_INCREMENT,
  `contactpnt0` VARCHAR(120) NULL DEFAULT NULL,
  `contactpnt1` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal0` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal1` VARCHAR(120) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `jawwidth` VARCHAR(45) NULL DEFAULT NULL,
  `quality` INT(11) NULL DEFAULT '0',
  `idobject` INT(11) NULL DEFAULT NULL,
  `idhand` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idfreeairgrip`),
  INDEX `idobject_idx` (`idobject` ASC),
  INDEX `freeairgrip_idhand_idx` (`idhand` ASC),
  CONSTRAINT `freeairgrip_idhand`
    FOREIGN KEY (`idhand`)
    REFERENCES `yumi`.`hand` (`idhand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `freeairgrip_idobject`
    FOREIGN KEY (`idobject`)
    REFERENCES `yumi`.`object` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`assemblyxgrips0`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`assemblyxgrips0` (
  `idassemblyxgrips0` INT(11) NOT NULL AUTO_INCREMENT,
  `contactpoint0` VARCHAR(120) NULL DEFAULT NULL,
  `contactpoint1` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal0` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal1` VARCHAR(120) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `jawwidth` VARCHAR(45) NULL DEFAULT NULL,
  `idassemblyx` INT(11) NULL DEFAULT NULL,
  `idfreeairgrip` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idassemblyxgrips0`),
  INDEX `idassembly_idx` (`idassemblyx` ASC),
  INDEX `assemblygrip0_idfreeairgrip_idx` (`idfreeairgrip` ASC),
  CONSTRAINT `assemblygrip0_idassemblyx`
    FOREIGN KEY (`idassemblyx`)
    REFERENCES `yumi`.`assemblyx` (`idassemblyx`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `assemblygrip0_idfreeairgrip`
    FOREIGN KEY (`idfreeairgrip`)
    REFERENCES `yumi`.`freeairgrip` (`idfreeairgrip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`assemblyxgrips1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`assemblyxgrips1` (
  `idassemblyxgrips1` INT(11) NOT NULL AUTO_INCREMENT,
  `contactpoint0` VARCHAR(120) NULL DEFAULT NULL,
  `contactpoint1` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal0` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal1` VARCHAR(120) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `jawwidth` VARCHAR(45) NULL DEFAULT NULL,
  `idassemblyx` INT(11) NULL DEFAULT NULL,
  `idfreeairgrip` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idassemblyxgrips1`),
  INDEX `idfreeairgrip_idx` (`idfreeairgrip` ASC),
  INDEX `assemblygrip1_idassemblyx_idx` (`idassemblyx` ASC),
  CONSTRAINT `assemblygrip1_idassemblyx`
    FOREIGN KEY (`idassemblyx`)
    REFERENCES `yumi`.`assemblyx` (`idassemblyx`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `assemblygrip1_idfreeairgrip`
    FOREIGN KEY (`idfreeairgrip`)
    REFERENCES `yumi`.`freeairgrip` (`idfreeairgrip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`assemblyxgrippairs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`assemblyxgrippairs` (
  `idassemblyxgrips0` INT(11) NOT NULL,
  `idassemblyxgrips1` INT(11) NOT NULL,
  PRIMARY KEY (`idassemblyxgrips0`, `idassemblyxgrips1`),
  INDEX `assemblyxgrippairs_idassemblyxgrips1_idx` (`idassemblyxgrips1` ASC),
  CONSTRAINT `assemblyxgrippairs_idassemblyxgrips0`
    FOREIGN KEY (`idassemblyxgrips0`)
    REFERENCES `yumi`.`assemblyxgrips0` (`idassemblyxgrips0`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `assemblyxgrippairs_idassemblyxgrips1`
    FOREIGN KEY (`idassemblyxgrips1`)
    REFERENCES `yumi`.`assemblyxgrips1` (`idassemblyxgrips1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`floatingposes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`floatingposes` (
  `idfloatingposes` INT(11) NOT NULL AUTO_INCREMENT,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `idobject` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idfloatingposes`),
  INDEX `object_idobject_idx` (`idobject` ASC),
  CONSTRAINT `floatingposes_idobject`
    FOREIGN KEY (`idobject`)
    REFERENCES `yumi`.`object` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`floatinggrips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`floatinggrips` (
  `idfloatinggrips` INT(11) NOT NULL AUTO_INCREMENT,
  `contactpoint0` VARCHAR(120) NULL DEFAULT NULL,
  `contactpoint1` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal0` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal1` VARCHAR(120) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `jawwidth` VARCHAR(45) NULL DEFAULT NULL,
  `idfloatingposes` INT(11) NULL DEFAULT NULL,
  `idfreeairgrip` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idfloatinggrips`),
  INDEX `freeairgrip_idfreeairgrip_idx` (`idfreeairgrip` ASC),
  INDEX `floatinggrips_idfloatingposes_idx` (`idfloatingposes` ASC),
  CONSTRAINT `floatinggrips_idfloatingposes`
    FOREIGN KEY (`idfloatingposes`)
    REFERENCES `yumi`.`floatingposes` (`idfloatingposes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `floatinggrips_idfreeairgrip`
    FOREIGN KEY (`idfreeairgrip`)
    REFERENCES `yumi`.`freeairgrip` (`idfreeairgrip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`floatinggripspairs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`floatinggripspairs` (
  `idfloatinggrips0` INT(11) NOT NULL,
  `idfloatinggrips1` INT(11) NOT NULL,
  PRIMARY KEY (`idfloatinggrips0`, `idfloatinggrips1`),
  INDEX `floatinggripspairs_id1_idx` (`idfloatinggrips1` ASC),
  CONSTRAINT `floatinggripspairs_id0`
    FOREIGN KEY (`idfloatinggrips0`)
    REFERENCES `yumi`.`floatinggrips` (`idfloatinggrips`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `floatinggripspairs_id1`
    FOREIGN KEY (`idfloatinggrips1`)
    REFERENCES `yumi`.`floatinggrips` (`idfloatinggrips`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'idfloatinggrippairs0 -- rgt, idfloatinggrippairs -- lft, right and left are saved in the table';

-- -----------------------------------------------------
-- Table `yumi`.`freetabletopplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`freetabletopplacement` (
  `idfreetabletopplacement` INT(11) NOT NULL AUTO_INCREMENT,
  `idobject` INT(11) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  PRIMARY KEY (`idfreetabletopplacement`),
  INDEX `freetabeltopplacement_idobject_idx` (`idobject` ASC),
  CONSTRAINT `freetabeltopplacement_idobject`
    FOREIGN KEY (`idobject`)
    REFERENCES `yumi`.`object` (`idobject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`freetabletopgrip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`freetabletopgrip` (
  `idfreetabletopgrip` INT(11) NOT NULL AUTO_INCREMENT,
  `contactpoint0` VARCHAR(120) NULL DEFAULT NULL,
  `contactpoint1` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal0` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal1` VARCHAR(120) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `jawwidth` VARCHAR(45) NULL DEFAULT NULL,
  `idfreetabletopplacement` INT(11) NULL DEFAULT NULL,
  `idfreeairgrip` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idfreetabletopgrip`),
  INDEX `freetabletopgrip_idfreeairgrip_idx` (`idfreeairgrip` ASC),
  INDEX `freetabletopgrip_idfreetabletopplacement_idx` (`idfreetabletopplacement` ASC),
  CONSTRAINT `freetabletopgrip_idfreeairgrip`
    FOREIGN KEY (`idfreeairgrip`)
    REFERENCES `yumi`.`freeairgrip` (`idfreeairgrip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `freetabletopgrip_idfreetabletopplacement`
    FOREIGN KEY (`idfreetabletopplacement`)
    REFERENCES `yumi`.`freetabletopplacement` (`idfreetabletopplacement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`robot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`robot` (
  `idrobot` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idrobot`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`tabletopplacements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`tabletopplacements` (
  `idtabletopplacements` INT(11) NOT NULL AUTO_INCREMENT,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `tabletopposition` VARCHAR(120) NULL DEFAULT NULL,
  `idfreetabletopplacement` INT(11) NULL DEFAULT NULL,
  `idangle` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idtabletopplacements`),
  INDEX `idangle_idx` (`idangle` ASC),
  INDEX `tabletopplacements_idfreetabletopplacement_idx` (`idfreetabletopplacement` ASC),
  CONSTRAINT `tabletopplacements_idangle`
    FOREIGN KEY (`idangle`)
    REFERENCES `yumi`.`angle` (`idangle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tabletopplacements_idfreetabletopplacement`
    FOREIGN KEY (`idfreetabletopplacement`)
    REFERENCES `yumi`.`freetabletopplacement` (`idfreetabletopplacement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`tabletopgrips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`tabletopgrips` (
  `idtabletopgrips` INT(11) NOT NULL AUTO_INCREMENT,
  `contactpnt0` VARCHAR(120) NULL DEFAULT NULL,
  `contactpnt1` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal0` VARCHAR(120) NULL DEFAULT NULL,
  `contactnormal1` VARCHAR(120) NULL DEFAULT NULL,
  `rotmat` VARCHAR(360) NULL DEFAULT NULL,
  `jawwidth` VARCHAR(45) NULL DEFAULT NULL,
  `idfreeairgrip` INT(11) NULL DEFAULT NULL,
  `idtabletopplacements` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idtabletopgrips`),
  INDEX `idtabletopplacements_idx` (`idtabletopplacements` ASC),
  INDEX `tabletopgrip_idfreeairgrip_idx` (`idfreeairgrip` ASC),
  CONSTRAINT `tabletopgrip_idfreeairgrip`
    FOREIGN KEY (`idfreeairgrip`)
    REFERENCES `yumi`.`freeairgrip` (`idfreeairgrip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tabletopgrip_idtabletopplacements`
    FOREIGN KEY (`idtabletopplacements`)
    REFERENCES `yumi`.`tabletopplacements` (`idtabletopplacements`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`iktabletopgrips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`iktabletopgrips` (
  `idrobot` INT(11) NOT NULL,
  `idarm` INT(11) NOT NULL,
  `idtabletopgrips` INT(11) NOT NULL,
  `feasibility` VARCHAR(45) NULL DEFAULT NULL,
  `feasibility_handa` VARCHAR(45) NULL DEFAULT NULL,
  `feasibility_worlda` VARCHAR(45) NULL DEFAULT NULL,
  `jnts` VARCHAR(360) NULL DEFAULT NULL,
  `jnts_handa` VARCHAR(360) NULL DEFAULT NULL,
  `jnts_worlda` VARCHAR(360) NULL DEFAULT NULL,
  PRIMARY KEY (`idrobot`, `idarm`, `idtabletopgrips`),
  INDEX `idrobot_idx` (`idrobot` ASC),
  INDEX `iktabletopgrips_idarm_idx` (`idarm` ASC),
  INDEX `iktabletopgrips_idtabletopgrips_idx` (`idtabletopgrips` ASC),
  CONSTRAINT `iktabletopgrips_idarm`
    FOREIGN KEY (`idarm`)
    REFERENCES `yumi`.`arm` (`idarm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `iktabletopgrips_idrobot`
    FOREIGN KEY (`idrobot`)
    REFERENCES `yumi`.`robot` (`idrobot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `iktabletopgrips_idtabletopgrips`
    FOREIGN KEY (`idtabletopgrips`)
    REFERENCES `yumi`.`tabletopgrips` (`idtabletopgrips`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`ikassemblyxgrips0`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`ikassemblyxgrips0` (
  `idrobot` INT(11) NOT NULL,
  `idarm` INT(11) NOT NULL,
  `idassemblyxgrips0` INT(11) NOT NULL,
  `feasibility` VARCHAR(45) NULL DEFAULT NULL,
  `feasibility_assdir` VARCHAR(45) NULL DEFAULT NULL,
  `jnts` VARCHAR(360) NULL DEFAULT NULL,
  `jnts_assdir` VARCHAR(360) NULL DEFAULT NULL,
  PRIMARY KEY (`idrobot`, `idarm`, `idassemblyxgrips0`),
  INDEX `ikassemblyxgrips0_idarm_idx` (`idarm` ASC),
  INDEX `ikassemblyxgrips0_idassemblyxgrips0_idx` (`idassemblyxgrips0` ASC),
  CONSTRAINT `ikassemblyxgrips0_idarm`
    FOREIGN KEY (`idarm`)
    REFERENCES `yumi`.`arm` (`idarm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ikassemblyxgrips0_idassemblyxgrips0`
    FOREIGN KEY (`idassemblyxgrips0`)
    REFERENCES `yumi`.`assemblyxgrips0` (`idassemblyxgrips0`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ikassemblyxgrips0_idrobot`
    FOREIGN KEY (`idrobot`)
    REFERENCES `yumi`.`robot` (`idrobot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`ikassemblyxgrips1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`ikassemblyxgrips1` (
  `idrobot` INT(11) NOT NULL,
  `idarm` INT(11) NOT NULL,
  `idassemblyxgrips1` INT(11) NOT NULL,
  `feasibility` VARCHAR(45) NULL DEFAULT NULL,
  `feasibility_assdir` VARCHAR(45) NULL DEFAULT NULL,
  `jnts` VARCHAR(360) NULL DEFAULT NULL,
  `jnts_assdir` VARCHAR(360) NULL DEFAULT NULL,
  PRIMARY KEY (`idrobot`, `idarm`, `idassemblyxgrips1`),
  INDEX `ikassemblyxgrips1_idarm_idx` (`idarm` ASC),
  INDEX `ikassemblyxgrips1_idassemblyxgrips1_idx` (`idassemblyxgrips1` ASC),
  CONSTRAINT `ikassemblyxgrips1_idarm`
    FOREIGN KEY (`idarm`)
    REFERENCES `yumi`.`arm` (`idarm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ikassemblyxgrips1_idassemblyxgrips1`
    FOREIGN KEY (`idassemblyxgrips1`)
    REFERENCES `yumi`.`assemblyxgrips1` (`idassemblyxgrips1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ikassemblyxgrips1_idrobot`
    FOREIGN KEY (`idrobot`)
    REFERENCES `yumi`.`robot` (`idrobot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`ikfloatinggrips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`ikfloatinggrips` (
  `idrobot` INT(11) NOT NULL,
  `idarm` INT(11) NOT NULL,
  `idfloatinggrips` INT(11) NOT NULL,
  `feasibility` VARCHAR(45) NULL DEFAULT NULL,
  `feasibility_handa` VARCHAR(45) NULL DEFAULT NULL,
  `jnts` VARCHAR(360) NULL DEFAULT NULL,
  `jnts_handa` VARCHAR(360) NULL DEFAULT NULL,
  PRIMARY KEY (`idrobot`, `idarm`, `idfloatinggrips`),
  INDEX `ikfloatinggrips_idarm_idx` (`idarm` ASC),
  INDEX `ikfloatinggrips_idfloatinggrips_idx` (`idfloatinggrips` ASC),
  CONSTRAINT `ikfloatinggrips_idarm`
    FOREIGN KEY (`idarm`)
    REFERENCES `yumi`.`arm` (`idarm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ikfloatinggrips_idfloatinggrips`
    FOREIGN KEY (`idfloatinggrips`)
    REFERENCES `yumi`.`floatinggrips` (`idfloatinggrips`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ikfloatinggrips_idrobot`
    FOREIGN KEY (`idrobot`)
    REFERENCES `yumi`.`robot` (`idrobot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `yumi`.`ikret`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yumi`.`ikret` (
  `idikret` INT(11) NOT NULL AUTO_INCREMENT,
  `rethanda` INT(11) NULL DEFAULT NULL,
  `retworlda` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idikret`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'the table saves the retraction distance for ik. the table is not connected to any other tables in the db. it is used as global parameters. metrics are in millimeter';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert basic values
-- -----------------------------------------------------
INSERT IGNORE `yumi`.`robot` VALUES(default, 'yumi');
INSERT IGNORE `yumi`.`hand` VALUES(default, 'yumiintegrated');
INSERT IGNORE `yumi`.`arm` VALUES(default, 'rgt'), (default, 'lft');
INSERT IGNORE `yumi`.`ikret` VALUES(default, 120, 70);
-- insert a few exemplary objects; add more if needed
INSERT IGNORE `yumi`.`object` VALUES(default, 'tubesmall');
INSERT IGNORE `yumi`.`object` VALUES(default, 'tubelarge');