# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from . import phoxi_pb2


class PhoxiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.triggerframe = channel.unary_unary(
        '/Phoxi/triggerframe',
        request_serializer=phoxi_pb2.Empty.SerializeToString,
        response_deserializer=phoxi_pb2.Empty.FromString,
        )
    self.gettextureimg = channel.unary_unary(
        '/Phoxi/gettextureimg',
        request_serializer=phoxi_pb2.Empty.SerializeToString,
        response_deserializer=phoxi_pb2.CamImg.FromString,
        )
    self.getdepthimg = channel.unary_unary(
        '/Phoxi/getdepthimg',
        request_serializer=phoxi_pb2.Empty.SerializeToString,
        response_deserializer=phoxi_pb2.CamImg.FromString,
        )
    self.getpcd = channel.unary_unary(
        '/Phoxi/getpcd',
        request_serializer=phoxi_pb2.Empty.SerializeToString,
        response_deserializer=phoxi_pb2.PointCloud.FromString,
        )
    self.getnormals = channel.unary_unary(
        '/Phoxi/getnormals',
        request_serializer=phoxi_pb2.Empty.SerializeToString,
        response_deserializer=phoxi_pb2.PointCloud.FromString,
        )


class PhoxiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def triggerframe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def gettextureimg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getdepthimg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getpcd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getnormals(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PhoxiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'triggerframe': grpc.unary_unary_rpc_method_handler(
          servicer.triggerframe,
          request_deserializer=phoxi_pb2.Empty.FromString,
          response_serializer=phoxi_pb2.Empty.SerializeToString,
      ),
      'gettextureimg': grpc.unary_unary_rpc_method_handler(
          servicer.gettextureimg,
          request_deserializer=phoxi_pb2.Empty.FromString,
          response_serializer=phoxi_pb2.CamImg.SerializeToString,
      ),
      'getdepthimg': grpc.unary_unary_rpc_method_handler(
          servicer.getdepthimg,
          request_deserializer=phoxi_pb2.Empty.FromString,
          response_serializer=phoxi_pb2.CamImg.SerializeToString,
      ),
      'getpcd': grpc.unary_unary_rpc_method_handler(
          servicer.getpcd,
          request_deserializer=phoxi_pb2.Empty.FromString,
          response_serializer=phoxi_pb2.PointCloud.SerializeToString,
      ),
      'getnormals': grpc.unary_unary_rpc_method_handler(
          servicer.getnormals,
          request_deserializer=phoxi_pb2.Empty.FromString,
          response_serializer=phoxi_pb2.PointCloud.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Phoxi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
