# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import robotconn.rpc.hndcam.hndcam_pb2 as hndcam__pb2


class CamStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getrc0img = channel.unary_unary(
        '/Cam/getrc0img',
        request_serializer=hndcam__pb2.Empty.SerializeToString,
        response_deserializer=hndcam__pb2.CamImg.FromString,
        )
    self.getrc1img = channel.unary_unary(
        '/Cam/getrc1img',
        request_serializer=hndcam__pb2.Empty.SerializeToString,
        response_deserializer=hndcam__pb2.CamImg.FromString,
        )
    self.getlc0img = channel.unary_unary(
        '/Cam/getlc0img',
        request_serializer=hndcam__pb2.Empty.SerializeToString,
        response_deserializer=hndcam__pb2.CamImg.FromString,
        )
    self.getlc1img = channel.unary_unary(
        '/Cam/getlc1img',
        request_serializer=hndcam__pb2.Empty.SerializeToString,
        response_deserializer=hndcam__pb2.CamImg.FromString,
        )


class CamServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getrc0img(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getrc1img(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getlc0img(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getlc1img(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CamServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getrc0img': grpc.unary_unary_rpc_method_handler(
          servicer.getrc0img,
          request_deserializer=hndcam__pb2.Empty.FromString,
          response_serializer=hndcam__pb2.CamImg.SerializeToString,
      ),
      'getrc1img': grpc.unary_unary_rpc_method_handler(
          servicer.getrc1img,
          request_deserializer=hndcam__pb2.Empty.FromString,
          response_serializer=hndcam__pb2.CamImg.SerializeToString,
      ),
      'getlc0img': grpc.unary_unary_rpc_method_handler(
          servicer.getlc0img,
          request_deserializer=hndcam__pb2.Empty.FromString,
          response_serializer=hndcam__pb2.CamImg.SerializeToString,
      ),
      'getlc1img': grpc.unary_unary_rpc_method_handler(
          servicer.getlc1img,
          request_deserializer=hndcam__pb2.Empty.FromString,
          response_serializer=hndcam__pb2.CamImg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Cam', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
